[package]
edition = "2021"
name = "ensure_no_std"
version = "0.1.0"

[dependencies]
bonsai-trie = { path = "../", default-features = false }
wee_alloc = "0.4.5"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
