on:
  pull_request:
  push:
    branches:
      - oss


name: Check and Lint and no-std

jobs:
  build-no-std:
    name: Build no-std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        working-directory: ./ensure_no_std
        run: rustup show
      - name: Build no-std
        run: cargo build
        
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Check format
        run: cargo fmt --check --all

  clippy-all-features:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Clippy all features
        run: cargo clippy --all-features

  clippy-default-features:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Clippy default features
        run: cargo clippy

  clippy-no-std:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Clippy no-std
        run: cargo clippy --no-default-features
