on:
  pull_request:
  push:
    branches:
      - oss


name: Check and Lint and wasm

jobs:
  build-wasm:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        working-directory: ./ensure_no_std
        run: rustup show
      - name: Build wasm
        run: cargo build
        
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Check format
        run: cargo fmt --check --all

  clippy-all-features:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Clippy all features
        run: cargo clippy --all-features

  clippy-default-features:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Clippy default features
        run: cargo clippy

  clippy-wasm:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup show
      - name: Clippy wasm
        run: cargo clippy --no-default-features
